"""Tool functions over the forecasting portfolio's JSON data.

Every tool is a pure lookup over the stored JSON. No tool runs a model,
extrapolates, or infers anything not already computed at build time in the
portfolio — and the agent is instructed to never do arithmetic itself, so
every number in an answer traces back to one of these returns.

Each decorated tool:
  - has ``strict=True`` so tool inputs validate exactly against the schema
    (``additionalProperties: false`` and ``required`` are generated by the SDK)
  - returns a JSON string (the serialized dict), because tool results are text
  - logs its call into ``CALL_LOG`` so the eval harness can score tool selection
"""

from __future__ import annotations

import json
from pathlib import Path

from anthropic import beta_tool

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# ---------------------------------------------------------------- data loading


def _load(name: str):
    with open(DATA_DIR / f"{name}.json") as f:
        return json.load(f)


_OVERALL = _load("planningOverall")
_DEPTS = _load("planningDepts")  # list of dicts, one per department
_TREND = _load("planningTrend")  # 38 weekly rows: week, fa, naiveFa
_SERIES = _load("deptSeries")  # dept -> 263 daily rows
_COMPARISON = _load("comparison")  # Prophet vs Elastic Net WAPE per dept
_PARETO = _load("pareto")  # revenue concentration curve

_DEPT_INDEX = {row["dept"]: row for row in _DEPTS}
_COMPARISON_INDEX = {row["dept"]: row for row in _COMPARISON}
VALID_DEPARTMENTS = sorted(_DEPT_INDEX)

_RANKABLE_METRICS = {
    "fa": "forecast accuracy (%)",
    "naive_fa": "seasonal-naive forecast accuracy (%)",
    "fva": "forecast value add (pp)",
    "bias": "signed bias (%)",
    "volume": "units sold over the backtest window",
}

# --------------------------------------------------------------- call logging

CALL_LOG: list[dict] = []


def reset_call_log() -> None:
    CALL_LOG.clear()


def _log(name: str, **inputs) -> None:
    CALL_LOG.append({"tool": name, "input": inputs})


def _dumps_logged(payload: dict | list) -> str:
    out = json.dumps(payload)
    if CALL_LOG:
        CALL_LOG[-1]["output"] = payload
    return out


# ------------------------------------------------------------------- helpers


def _unknown_dept(dept: str) -> dict:
    return {
        "error": f"Unknown department '{dept}'.",
        "valid_departments": VALID_DEPARTMENTS,
    }


def _dumps(payload: dict | list) -> str:
    return json.dumps(payload)


# --------------------------------------------------------------------- tools


@beta_tool(strict=True)
def list_departments() -> str:
    """List the seven departments in the backtest with their unit volumes.

    Volume is total units sold over the 263-day backtest window; use it to
    judge how much a department matters. Call this first when you need to
    know what departments exist or to resolve a partial department name.
    """
    _log("list_departments")
    return _dumps_logged(
        {
            "departments": [
                {"dept": row["dept"], "volume_units": row["volume"]} for row in _DEPTS
            ],
            "note": "volume_units is total units sold over the 263-day backtest window",
        }
    )


@beta_tool(strict=True)
def get_overall() -> str:
    """Pooled headline metrics for the whole backtest (all departments together).

    Returns forecast accuracy, seasonal-naive accuracy, forecast value add in
    percentage points, signed bias, total units, and how many of the seven
    departments beat the naive baseline.
    """
    _log("get_overall")
    return _dumps_logged(
        {
            "forecast_accuracy_pct": _OVERALL["fa"],
            "naive_accuracy_pct": _OVERALL["naiveFa"],
            "forecast_value_add_pp": _OVERALL["fva"],
            "bias_pct": _OVERALL["bias"],
            "total_units": _OVERALL["units"],
            "departments_beating_naive": _OVERALL["improved"],
            "departments_total": _OVERALL["total"],
        }
    )


@beta_tool(strict=True)
def get_accuracy(dept: str) -> str:
    """Forecast accuracy for one department, next to its seasonal-naive baseline.

    Args:
        dept: Department name, e.g. FOODS_3. Use list_departments for the
            valid names.
    """
    _log("get_accuracy", dept=dept)
    row = _DEPT_INDEX.get(dept)
    if row is None:
        return _dumps_logged(_unknown_dept(dept))
    return _dumps_logged(
        {
            "dept": dept,
            "forecast_accuracy_pct": row["fa"],
            "naive_accuracy_pct": row["naiveFa"],
        }
    )


@beta_tool(strict=True)
def get_value_add(dept: str) -> str:
    """Forecast value add for one department, in percentage points.

    Positive means the model beats the seasonal-naive baseline; negative
    means repeating last week's same weekday would have been more accurate.

    Args:
        dept: Department name, e.g. FOODS_3.
    """
    _log("get_value_add", dept=dept)
    row = _DEPT_INDEX.get(dept)
    if row is None:
        return _dumps_logged(_unknown_dept(dept))
    return _dumps_logged(
        {
            "dept": dept,
            "forecast_value_add_pp": row["fva"],
            "beats_naive": row["fva"] > 0,
        }
    )


@beta_tool(strict=True)
def get_bias(dept: str) -> str:
    """Signed forecast bias for one department, in percent.

    Positive bias means the model over-forecasts (predicts more than sold);
    negative means it under-forecasts.

    Args:
        dept: Department name, e.g. FOODS_3.
    """
    _log("get_bias", dept=dept)
    row = _DEPT_INDEX.get(dept)
    if row is None:
        return _dumps_logged(_unknown_dept(dept))
    return _dumps_logged(
        {
            "dept": dept,
            "bias_pct": row["bias"],
            "direction": "over-forecasting" if row["bias"] > 0 else "under-forecasting",
        }
    )


@beta_tool(strict=True)
def get_series(dept: str, days: int) -> str:
    """Recent daily rows for one department: actual vs model vs naive units.

    Args:
        dept: Department name, e.g. FOODS_3.
        days: How many of the most recent days to return, between 1 and 60.
    """
    _log("get_series", dept=dept, days=days)
    rows = _SERIES.get(dept)
    if rows is None:
        return _dumps_logged(_unknown_dept(dept))
    if not 1 <= days <= 60:
        return _dumps_logged({"error": "days must be between 1 and 60"})
    recent = rows[-days:]
    return _dumps_logged(
        {
            "dept": dept,
            "days_returned": len(recent),
            "window": {"from": recent[0]["date"], "to": recent[-1]["date"]},
            "rows": [
                {
                    "date": r["date"],
                    "actual_units": r["actual"],
                    "model_units": r["model"],
                    "naive_units": r["naive"],
                    "abs_error_units": r["err"],
                }
                for r in recent
            ],
        }
    )


@beta_tool(strict=True)
def compare_departments(metric: str) -> str:
    """All seven departments ranked on one metric, best first.

    Args:
        metric: One of "fa" (forecast accuracy), "naive_fa" (baseline
            accuracy), "fva" (forecast value add), "bias" (signed bias,
            ranked by magnitude closest to zero first), or "volume"
            (units sold).
    """
    _log("compare_departments", metric=metric)
    if metric not in _RANKABLE_METRICS:
        return _dumps_logged(
            {
                "error": f"Unknown metric '{metric}'.",
                "valid_metrics": sorted(_RANKABLE_METRICS),
            }
        )
    key = {"naive_fa": "naiveFa"}.get(metric, metric)
    if metric == "bias":
        ranked = sorted(_DEPTS, key=lambda r: abs(r[key]))
    else:
        ranked = sorted(_DEPTS, key=lambda r: r[key], reverse=True)
    return _dumps_logged(
        {
            "metric": metric,
            "metric_description": _RANKABLE_METRICS[metric],
            "order": "best first"
            if metric != "bias"
            else "closest to zero (least biased) first",
            "ranking": [{"dept": r["dept"], "value": r[key]} for r in ranked],
        }
    )


@beta_tool(strict=True)
def get_weekly_trend(weeks: int) -> str:
    """Weekly forecast accuracy vs the naive baseline over time.

    Args:
        weeks: How many of the most recent weeks to return, between 1 and 38.
    """
    _log("get_weekly_trend", weeks=weeks)
    if not 1 <= weeks <= 38:
        return _dumps_logged({"error": "weeks must be between 1 and 38"})
    recent = _TREND[-weeks:]
    return _dumps_logged(
        {
            "weeks_returned": len(recent),
            "rows": [
                {
                    "week_starting": r["week"],
                    "forecast_accuracy_pct": r["fa"],
                    "naive_accuracy_pct": r["naiveFa"],
                }
                for r in recent
            ],
        }
    )


@beta_tool(strict=True)
def get_model_comparison(dept: str) -> str:
    """Prophet vs Elastic Net WAPE for one department, from the backtest study.

    Note: this is a separate benchmark from the planning metrics — Prophet ran
    on daily data and Elastic Net on monthly aggregates, so the two WAPEs are
    not directly comparable to each other or to the planning accuracy figures.

    Args:
        dept: Department name, e.g. FOODS_3.
    """
    _log("get_model_comparison", dept=dept)
    row = _COMPARISON_INDEX.get(dept)
    if row is None:
        return _dumps_logged(_unknown_dept(dept))
    return _dumps_logged(
        {
            "dept": dept,
            "prophet_wape_pct_daily": row["prophetWape"],
            "elastic_net_wape_pct_monthly": row["elasticWape"],
            "mean_daily_units": row["meanDaily"],
            "caveat": "daily and monthly WAPE are not directly comparable",
        }
    )


@beta_tool(strict=True)
def get_revenue_concentration(top_items_pct: int) -> str:
    """Share of realised revenue covered by the top N% of SKUs.

    The curve is stored at fixed grid points; top_items_pct must be one of
    them.

    Args:
        top_items_pct: Percentage of the 3,049 SKUs, e.g. 20 for the top 20%.
            Valid values are the stored grid points (multiples of 5 up to 100).
    """
    _log("get_revenue_concentration", top_items_pct=top_items_pct)
    for point in _PARETO:
        if point["itemsPct"] == top_items_pct:
            return _dumps_logged(
                {
                    "top_items_pct": top_items_pct,
                    "revenue_pct": point["revenuePct"],
                    "total_skus": 3049,
                }
            )
    return _dumps_logged(
        {
            "error": f"No stored grid point at {top_items_pct}%.",
            "valid_values": [p["itemsPct"] for p in _PARETO],
        }
    )


def _window_metrics(rows: list[dict]) -> dict:
    total_actual = sum(r["actual"] for r in rows)
    if total_actual == 0:
        return {"error": "no sales in this window; accuracy is undefined"}
    wape_model = 100 * sum(abs(r["actual"] - r["model"]) for r in rows) / total_actual
    wape_naive = 100 * sum(abs(r["actual"] - r["naive"]) for r in rows) / total_actual
    fa = round(100 - wape_model, 1)
    naive_fa = round(100 - wape_naive, 1)
    return {
        "days": len(rows),
        "forecast_accuracy_pct": fa,
        "naive_accuracy_pct": naive_fa,
        "forecast_value_add_pp": round(fa - naive_fa, 1),
    }


@beta_tool(strict=True)
def get_window_accuracy(dept: str, start_date: str, end_date: str) -> str:
    """Forecast accuracy vs the naive baseline for one department in a date window.

    Computed deterministically from the stored daily series (WAPE over the
    window). The data covers 2013-05-05 to 2014-01-22; windows outside that
    range return an error rather than an estimate.

    Args:
        dept: Department name, e.g. FOODS_3.
        start_date: Window start, ISO format YYYY-MM-DD (inclusive).
        end_date: Window end, ISO format YYYY-MM-DD (inclusive).
    """
    _log("get_window_accuracy", dept=dept, start_date=start_date, end_date=end_date)
    rows = _SERIES.get(dept)
    if rows is None:
        return _dumps_logged(_unknown_dept(dept))
    window = [r for r in rows if start_date <= r["date"] <= end_date]
    if not window:
        return _dumps_logged(
            {
                "error": f"No data in {start_date}..{end_date}.",
                "data_range": {"from": rows[0]["date"], "to": rows[-1]["date"]},
            }
        )
    result = _window_metrics(window)
    result.update({"dept": dept, "window": {"from": window[0]["date"], "to": window[-1]["date"]}})
    return _dumps_logged(result)


@beta_tool(strict=True)
def get_fold_accuracy(dept: str, fold: int) -> str:
    """Forecast accuracy vs naive for one walk-forward backtest fold.

    The backtest has three sequential folds (1, 2, 3); comparing them shows
    whether the model's edge grows or shrinks as the backtest advances.

    Args:
        dept: Department name, e.g. FOODS_3.
        fold: Fold number: 1, 2, or 3.
    """
    _log("get_fold_accuracy", dept=dept, fold=fold)
    rows = _SERIES.get(dept)
    if rows is None:
        return _dumps_logged(_unknown_dept(dept))
    if fold not in (1, 2, 3):
        return _dumps_logged({"error": "fold must be 1, 2, or 3"})
    subset = [r for r in rows if r["fold"] == fold]
    result = _window_metrics(subset)
    result.update(
        {"dept": dept, "fold": fold, "window": {"from": subset[0]["date"], "to": subset[-1]["date"]}}
    )
    return _dumps_logged(result)


@beta_tool(strict=True)
def get_worst_days(dept: str, n: int) -> str:
    """The n days with the largest absolute forecast error for one department.

    Args:
        dept: Department name, e.g. FOODS_3.
        n: How many days to return, between 1 and 10.
    """
    _log("get_worst_days", dept=dept, n=n)
    rows = _SERIES.get(dept)
    if rows is None:
        return _dumps_logged(_unknown_dept(dept))
    if not 1 <= n <= 10:
        return _dumps_logged({"error": "n must be between 1 and 10"})
    worst = sorted(rows, key=lambda r: -r["err"])[:n]
    return _dumps_logged(
        {
            "dept": dept,
            "worst_days": [
                {
                    "date": r["date"],
                    "actual_units": r["actual"],
                    "model_units": r["model"],
                    "naive_units": r["naive"],
                    "abs_error_units": r["err"],
                    "naive_abs_error_units": round(abs(r["actual"] - r["naive"]), 1),
                }
                for r in worst
            ],
        }
    )


ALL_TOOLS = [
    list_departments,
    get_overall,
    get_accuracy,
    get_value_add,
    get_bias,
    get_series,
    compare_departments,
    get_weekly_trend,
    get_model_comparison,
    get_revenue_concentration,
    get_window_accuracy,
    get_fold_accuracy,
    get_worst_days,
]
